### ISSUE TITLE
Update examples to use latest version of the charting library

### ISSUE THREAD

**Issue by senzacionale** [tradingview/charting-library-examples#113]
```
ERROR in src/app/tv-chart-container/tv-chart-container.component.ts(4,5): error TS2305: Module '"C:/Users/mitja/Downloads/charting-library-examples-3fabf861de413f8ca4a32ad0df72ea6c2a0909a0/angular5/src/assets/charting_library/charting_library.min"' has no exported member 'onready'.
src/app/tv-chart-container/tv-chart-container.component.ts(113,22): error TS2339: Property 'attr' does not exist on type 'HTMLElement'.
```

Can someone help what to fix?

**Comment by timocov** [comment]
We'll need to update examples to use the latest version of the library. Currently they should work with 1.12 and 1.13 versions of the library (I believe). In 1.14 we've removed that function.
